### ISSUE TITLE
EVN Leistungsfaktor leads to exception

### ISSUE THREAD

**Issue by martin-at-schorsch** [NECH2004/smartmeter_austria_energy#3]
EVN Value Leistungsfaktor results in an exception as the physical unit 255 is not defined in class PhysicalUnits(Enum).

adding NoUnit = 0xFF solves the problem.

The example of EVN includes Leistungsfaktor OBIS - 1.0.13.7.0.255 with the datatype.
https://www.netz-noe.at/Download-(1)/Smart-Meter/218_9_SmartMeter_Kundenschnittstelle_lektoriert_14.aspx

I tested it with a Sagemcom T210-D.

**Comment by NECH2004** [comment]
merged
